"""Add UserRecipe and RecipeNutrient tables

Revision ID: c7e58f6ac88b
Revises: 0cbbf319e161
Create Date: 2024-11-15 16:59:35.517203

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c7e58f6ac88b'
down_revision = '0cbbf319e161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_nutrient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('nutrient_id', sa.Integer(), nullable=False),
    sa.Column('amount_per_serving', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['nutrient_id'], ['nutrient.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('nutrient_units')
        batch_op.drop_column('comparison_to_rni')
        batch_op.drop_column('micro_nutrients_per_serving')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('micro_nutrients_per_serving', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('comparison_to_rni', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nutrient_units', postgresql.BYTEA(), autoincrement=False, nullable=True))

    op.drop_table('recipe_nutrient')
    op.drop_table('nutrient')
    # ### end Alembic commands ###
