"""empty message

Revision ID: f7de5fde7a94
Revises: e03186ea3501
Create Date: 2024-12-07 16:16:22.008440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7de5fde7a94'
down_revision = 'e03186ea3501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_nutrient', schema=None) as batch_op:
        batch_op.drop_constraint('recipe_nutrient_nutrient_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('recipe_nutrient_recipe_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'nutrient', ['nutrient_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_recipe', schema=None) as batch_op:
        batch_op.drop_constraint('user_recipe_recipe_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_recipe', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_recipe_recipe_id_fkey', 'recipe', ['recipe_id'], ['id'])

    with op.batch_alter_table('recipe_nutrient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recipe_nutrient_recipe_id_fkey', 'recipe', ['recipe_id'], ['id'])
        batch_op.create_foreign_key('recipe_nutrient_nutrient_id_fkey', 'nutrient', ['nutrient_id'], ['id'])

    # ### end Alembic commands ###
